// Turns a single user-picked background color into a full brand-* ramp
// (the same 11-step neutral scale the hand-tuned Coral/Midnight/Sage
// themes each define in globals.css) plus a matching foreground, so
// "custom" theming only ever asks for one color and every other surface,
// border and text tone follows from it automatically.
//
// The two hand-tuned families this mirrors: light-leaning themes (Coral,
// Sage) set brand-50 to their exact background and brand-900 to their
// exact foreground; dark-leaning themes (Midnight) do the reverse
// (brand-900 = background, brand-50 = foreground). Whichever the picked
// color's own lightness resembles, the rest of the ramp is generated by
// easing lightness toward the opposite extreme while holding hue and
// saturation constant.

export type RampStep =
  | "50"
  | "100"
  | "200"
  | "300"
  | "400"
  | "500"
  | "600"
  | "700"
  | "800"
  | "900"
  | "950";

const STEPS: RampStep[] = [
  "50",
  "100",
  "200",
  "300",
  "400",
  "500",
  "600",
  "700",
  "800",
  "900",
  "950",
];

export interface GeneratedTheme {
  isDark: boolean;
  background: string;
  foreground: string;
  ramp: Record<RampStep, string>;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function hexToHsl(hex: string): { h: number; s: number; l: number } {
  const normalized = hex.replace("#", "");
  const r = parseInt(normalized.slice(0, 2), 16) / 255;
  const g = parseInt(normalized.slice(2, 4), 16) / 255;
  const b = parseInt(normalized.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  const delta = max - min;

  let h = 0;
  let s = 0;
  if (delta !== 0) {
    s = delta / (1 - Math.abs(2 * l - 1));
    switch (max) {
      case r:
        h = ((g - b) / delta) % 6;
        break;
      case g:
        h = (b - r) / delta + 2;
        break;
      default:
        h = (r - g) / delta + 4;
    }
    h *= 60;
    if (h < 0) h += 360;
  }
  return { h, s: s * 100, l: l * 100 };
}

function hslToHex(h: number, s: number, l: number): string {
  const sNorm = s / 100;
  const lNorm = l / 100;
  const c = (1 - Math.abs(2 * lNorm - 1)) * sNorm;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = lNorm - c / 2;

  let r = 0;
  let g = 0;
  let b = 0;
  if (h < 60) [r, g, b] = [c, x, 0];
  else if (h < 120) [r, g, b] = [x, c, 0];
  else if (h < 180) [r, g, b] = [0, c, x];
  else if (h < 240) [r, g, b] = [0, x, c];
  else if (h < 300) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];

  const toHex = (channel: number) =>
    Math.round((channel + m) * 255)
      .toString(16)
      .padStart(2, "0");
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

// Is the picked color itself dark? Under 50% lightness reads as dark-leaning
// (background should sit near the dark end of the ramp, like Midnight);
// otherwise light-leaning (background near the light end, like Coral/Sage).
export function isColorDark(hex: string): boolean {
  return hexToHsl(hex).l < 50;
}

export function generateThemeFromColor(hex: string): GeneratedTheme {
  const { h, s, l } = hexToHsl(hex);
  const isDark = l < 50;

  // The background anchor is clamped to a safe extreme rather than using
  // the picked/extracted color's raw lightness verbatim — mirrors how
  // every hand-tuned theme (Coral, Sage, Midnight) is built: a
  // light-leaning background sits very light (~90%+) and a dark-leaning
  // one very dark (~12%-), which is what actually gives every other ramp
  // step (muted text, borders, links) enough headroom to stay legible.
  // A photo's dominant color is often only medium-lightness — technically
  // "light-leaning" by the <50 test above, but nowhere near light enough
  // to generate readable secondary text on top of it, which is exactly
  // what produced washed-out timestamps/links/placeholders on a
  // photo-extracted medium purple.
  const anchorL = isDark ? Math.min(l, 12) : Math.max(l, 90);
  const ramp = {} as Record<RampStep, string>;

  if (!isDark) {
    // brand-50 = the lightness-anchored color; ease down to a near-black
    // floor by brand-950, same shape as Coral/Sage.
    const floor = 9;
    STEPS.forEach((step, i) => {
      const t = i / (STEPS.length - 1);
      const eased = Math.pow(t, 1.5);
      const stepL = anchorL - (anchorL - floor) * eased;
      ramp[step] = hslToHex(h, s, clamp(stepL, floor, 99));
    });
  } else {
    // brand-900 = the lightness-anchored color; ease up to a near-white
    // ceiling by brand-50, with brand-950 as a darker floor below the
    // background — same shape as Midnight.
    const ceiling = 92;
    const idx900 = STEPS.indexOf("900");
    STEPS.forEach((step, i) => {
      if (step === "950") {
        ramp[step] = hslToHex(h, s, clamp(anchorL * 0.65, 3, 97));
        return;
      }
      const t = i / idx900;
      const eased = Math.pow(t, 1.5);
      const stepL = ceiling - (ceiling - anchorL) * eased;
      ramp[step] = hslToHex(h, s, clamp(stepL, 3, 97));
    });
  }

  return {
    isDark,
    background: ramp[isDark ? "900" : "50"],
    foreground: ramp[isDark ? "50" : "900"],
    ramp,
  };
}
